### ISSUE TITLE
Recent link loading

### ISSUE THREAD

**Issue by WhereBeTheDan** [mkdo/link-picker-for-cmb2#1]
First off, great addon to cmb! 

I am having some js issues when the modal opens, specifically that items are not autoloaded. There is a console error: `wplink.js:169 Uncaught TypeError: Cannot read property 'selectionStart' of undefined` which looks related to no editor id being passed to the `wpLink.open()` call. Adding the id of the url input like `wpLink.open('wp-link-url')` resolved the issue for me.

**Comment by mattwatsoncodes** [comment]
Thats @WhereBeTheDan, I'll take a look. 

Do you have the text editor on that page? Some people have pointed out that if you don't have a text editor the plugin fires up these kinds of errors. I'm just wondering if the issues are related.

**Comment by WhereBeTheDan** [comment]
Yes, I have the default page tinymce editor. The issue is occurring both inside and outside of grouped fields. Also not sure if this would matter, but I'm also running cmb2-grid, cmb2-attached-posts, and cmb2-conditionals. One thing that just caught my eye: what is the purpose of setting `wpActiveEditor = true;` right before`wpLink.open();`? Isn't that overwriting the value of `window.wpActiveEditor`, which `wpLink` is using to build it's `textarea` property? Removing that line also resolves the issue, but I'm not sure if it's needed for something else.

**Comment by mattwatsoncodes** [comment]
You have a point @WhereBeTheDan. Happy for you to submit a PR if you like? If not I'll take care of it as soon as I get 5 mins (likely next week).

**Comment by WhereBeTheDan** [comment]
Submitted, hopefully I did it right, my first time submitting a PR.

**Comment by mattwatsoncodes** [comment]
Thanks @WhereBeTheDan what is your WP username so I can add you as a contributor?

I'll test and merge as soon as I can (one of those days).

**Comment by WhereBeTheDan** [comment]
Username is sagetopia (I assume you mean for Wordpress.org?). No rush on merging, thanks again for the plugin.

**Comment by mattwatsoncodes** [comment]
Cheers @WhereBeTheDan that fixed the issue. I'll update the WP repo shortly.
